# Generated by Django 4.0.4 on 2022-06-10 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='posts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followersPosts', to='network.post'),
            preserve_default=False,
        ),
    ]
