# Generated by Django 4.0.4 on 2022-06-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_follower_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='posts',
        ),
    ]
