# Generated by Django 4.0.5 on 2022-06-15 12:03

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_follower_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userColour',
            field=colorful.fields.RGBColorField(default='red'),
            preserve_default=False,
        ),
    ]
