# Generated by Django 4.0.5 on 2022-07-23 17:04

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_user_usercolour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userColour',
            field=colorful.fields.RGBColorField(default='#FF9000'),
        ),
    ]
